#
# INSTALL NODE CONTROLLER(s) AND TUNE
#
 
- hosts: nc
  vars_files: 
    - vars/nc-vars.yml
    - ../../rhn.yml
  vars:
    do_rhn_reg: "'$register_with_rhn' == 'yes'"
       
  tasks:

  - name: Downloads the repo RPMs
    action: get_url url=$item dest=/tmp/ thirsty=yes
    with_items:
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/eucalyptus-release-${euca_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/euca2ools/${eucatools_version}/rhel/6/x86_64/euca2ools-release-${eucatools_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/epel-release-6.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/elrepo-release-6.noarch.rpm
    tags:
    - geturl

  - name: Install the repo RPMs
    action: command rpm -Uvh --force /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm
    
  - name: Tidy up
    action: command rm /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm
    
  - name: Register with RHN for dependencies
    action: command rhnreg_ks --username $rhn_username --password $rhn_password 
    only_if: '$do_rhn_reg'
    ignore_errors: True

  - name: Install the Eucalyptus RPMs and deps
    action: yum pkg=$item state=installed
    with_items:
    - eucalyptus-enterprise-release
    - eucalyptus-nc
    - libselinux-python
    - tuned
    tags:
    - packages   
   
  - name: disable firewall
    action: service name=iptables enabled=no state=stopped
    tags: networking
    
#  - name: old read MAC address for interface to add to the bridge
#    action: command ifconfig em1 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'
##    register: mac
#   tags: networking
    
#  - name: insert MAC address for desired interface
##    action: lineinfile dest=/etc/sysconfig/network-scripts/ifcfg-${bridge} regexp=^HWADDR line=HWADDR="\"${mac.rc}\""
 ##   tags: template
    
  - name: checking existing networking configuration
    action: shell /sbin/ifconfig $bridge
    register: bridge_exists
    ignore_errors: true
    tags: networking
    
  - name: template the interface file
    action: template src=templates/ifconfig_bridge_interface.j2 dest=/etc/sysconfig/network-scripts/ifcfg-${bridge_iface}
    only_if: "'${bridge_exists.rc}' == '1'"
    tags: networking
    
  - name: template the bridge interface file
    action: template src=templates/ifconfig_bridge.j2 dest=/etc/sysconfig/network-scripts/ifcfg-${bridge}
    only_if: "'${bridge_exists.rc}' == '1'"
    tags: networking
  
  - name: restart networking
    action: service name=network enabled=yes state=restarted
    tags: networking
 
  - name: modprobe kvm modules
    action: shell /sbin/modprobe kvm_intel
    only_if: "'$hypervisor' == 'kvm'"
    register: kvm_loaded
    tags: tune
    
  - name: Fail on lack of VT
    action: fail msg="VT is not enabled on this system, please enable it in the system BIOS before proceeding."
    only_if: "'${kvm_loaded.rc}' == '1'"
    tags: tune
  
  - name: Ensure SElinux is disabled
    action: selinux state=disabled
    tags: tune
    
  - name: set profile
    action: command tuned-adm profile $tuned_profile
    tags: tune

  - name: set tuned to start on boot
    action: service name=tuned enabled=yes state=started
    tags: tune

  - name: turn on ntp and start on boot
    action: service name=ntpd enabled=yes state=started
    tags: tune
    
# 
# INSTALL CLUSTER CONTROLLER(s) AND TUNE
#

- hosts: cc
  vars_files:
    - vars/cc-vars.yml
    - ../../rhn.yml
  vars:
    do_rhn_reg: "'$register_with_rhn' == 'yes'"

  tasks:

  - name: Downloads the repo RPMs
    action: get_url url=$item dest=/tmp/ thirsty=yes
    with_items:
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/eucalyptus-release-${euca_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/euca2ools/${eucatools_version}/rhel/6/x86_64/euca2ools-release-${eucatools_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/epel-release-6.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/elrepo-release-6.noarch.rpm
    tags:
    - geturl

  - name: Install the repo RPMs
    action: command rpm -Uvh --force /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm

  - name: Tidy up
    action: command rm /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm

  - name: Register with RHN for dependencies
    action: command rhnreg_ks --username $rhn_username --password $rhn_password
    only_if: '$do_rhn_reg'
    ignore_errors: True

  - name: Install the Eucalyptus RPMs and deps
    action: yum pkg=$item state=installed
    with_items:
    - eucalyptus-enterprise-release
    - eucalyptus-cc
    - libselinux-python
    - tuned
    tags:
    - packages

  - name: disable firewall
    action: service name=iptables enabled=no state=stopped
    tags: networking

  - name: Ensure SElinux is disabled
    action: selinux state=disabled
    tags: tune

  - name: set profile
    action: command tuned-adm profile $tuned_profile
    tags: tune

  - name: set tuned to start on boot
    action: service name=tuned enabled=yes state=started
    tags: tune

  - name: turn on ntp and start on boot
    action: service name=ntpd enabled=yes state=started
    tags: tune

# 
# INSTALL STORAGE CONTROLLER(s) AND TUNE
#

- hosts: sc
  vars_files:
    - vars/sc-vars.yml
    - ../../rhn.yml
  vars:
    do_rhn_reg: "'$register_with_rhn' == 'yes'"

  tasks:

  - name: Downloads the repo RPMs
    action: get_url url=$item dest=/tmp/ thirsty=yes
    with_items:
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/eucalyptus-release-${euca_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/euca2ools/${eucatools_version}/rhel/6/x86_64/euca2ools-release-${eucatools_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/epel-release-6.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/elrepo-release-6.noarch.rpm
    tags:
    - geturl

  - name: Install the repo RPMs
    action: command rpm -Uvh --force /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm

  - name: Tidy up
    action: command rm /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm

  - name: Register with RHN for dependencies
    action: command rhnreg_ks --username $rhn_username --password $rhn_password
    only_if: '$do_rhn_reg'
    ignore_errors: True

 - name: Install the Eucalyptus RPMs and deps
    action: yum pkg=$item state=installed
    with_items:
    - eucalyptus-enterprise-release
    - eucalyptus-sc
    - libselinux-python
    - tuned
    tags:
    - packages

  - name: disable firewall
    action: service name=iptables enabled=no state=stopped
    tags: networking

  - name: Ensure SElinux is disabled
    action: selinux state=disabled
    tags: tune

  - name: set profile
    action: command tuned-adm profile $tuned_profile
    tags: tune

  - name: set tuned to start on boot
    action: service name=tuned enabled=yes state=started
    tags: tune

  - name: turn on ntp and start on boot
    action: service name=ntpd enabled=yes state=started
    tags: tune

# 
# INSTALL WALRUS(es) AND TUNE
#

- hosts: walrus
  vars_files:
    - vars/walrus-vars.yml
    - ../../rhn.yml
  vars:
    do_rhn_reg: "'$register_with_rhn' == 'yes'"

  tasks:

  - name: Downloads the repo RPMs
    action: get_url url=$item dest=/tmp/ thirsty=yes
    with_items:
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/eucalyptus-release-${euca_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/euca2ools/${eucatools_version}/rhel/6/x86_64/euca2ools-release-${eucatools_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/epel-release-6.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/elrepo-release-6.noarch.rpm
    tags:
    - geturl

  - name: Install the repo RPMs
    action: command rpm -Uvh --force /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm

  - name: Tidy up
    action: command rm /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm

  - name: Register with RHN for dependencies
    action: command rhnreg_ks --username $rhn_username --password $rhn_password
    only_if: '$do_rhn_reg'
    ignore_errors: True

  - name: Install the Eucalyptus RPMs and deps
    action: yum pkg=$item state=installed
    with_items:
    - eucalyptus-enterprise-release
    - eucalyptus-walrus
    - libselinux-python
    - tuned
    tags:
    - packages

  - name: disable firewall
    action: service name=iptables enabled=no state=stopped
    tags: networking

  - name: Ensure SElinux is disabled
    action: selinux state=disabled
    tags: tune

  - name: set profile
    action: command tuned-adm profile $tuned_profile
    tags: tune

  - name: set tuned to start on boot
    action: service name=tuned enabled=yes state=started
    tags: tune

  - name: turn on ntp and start on boot
    action: service name=ntpd enabled=yes state=started
    tags: tune

# 
# INSTALL CLOUD CONTROLLER(s) AND TUNE
#

- hosts: clc
  vars_files:
    - vars/clc-vars.yml
    - ../../rhn.yml
  vars:
    do_rhn_reg: "'$register_with_rhn' == 'yes'"

  tasks:

  - name: Downloads the repo RPMs
    action: get_url url=$item dest=/tmp/ thirsty=yes
    with_items:
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/eucalyptus-release-${euca_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/euca2ools/${eucatools_version}/rhel/6/x86_64/euca2ools-release-${eucatools_version}.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/epel-release-6.noarch.rpm
    - http://downloads.eucalyptus.com/software/eucalyptus/${euca_version}/rhel/6/x86_64/elrepo-release-6.noarch.rpm
    tags:
    - geturl

  - name: Install the repo RPMs
    action: command rpm -Uvh --force /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm

  - name: Tidy up
    action: command rm /tmp/$item
    with_items:
    - eucalyptus-release-${euca_version}.noarch.rpm
    - euca2ools-release-${eucatools_version}.noarch.rpm
    - epel-release-6.noarch.rpm
    - elrepo-release-6.noarch.rpm

  - name: Register with RHN for dependencies
    action: command rhnreg_ks --username $rhn_username --password $rhn_password
    only_if: '$do_rhn_reg'
    ignore_errors: True

  - name: Install the Eucalyptus RPMs and deps
    action: yum pkg=$item state=installed
    with_items:
    - eucalyptus-enterprise-release
    - eucalyptus-cloud
    - libselinux-python
    - tuned
    tags:
    - packages

  - name: disable firewall
    action: service name=iptables enabled=no state=stopped
    tags: networking

  - name: Ensure SElinux is disabled
    action: selinux state=disabled
    tags: tune

  - name: set profile
    action: command tuned-adm profile $tuned_profile
    tags: tune

  - name: set tuned to start on boot
    action: service name=tuned enabled=yes state=started
    tags: tune

  - name: turn on ntp and start on boot
    action: service name=ntpd enabled=yes state=started
    tags: tune

#
# CONFIGURE COMPONENTS
#

- hosts: clc,walrus,cc,sc,nc
  vars_files:
    - vars/global-vars.yml

  tasks:

  - name: Set global network mode 
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_MODE= line=VNET_MODE="\"$network_mode\""
    tags: conf

- hosts: nc
  vars_files:
    - vars/nc-vars.yml

  tasks:

  - name: set NC port
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^NC_PORT line=NC_PORT="\"$nc_port\""
    tags: conf

  - name: set Hypervisor
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^HYPERVISOR= line=HYPERVISOR="\"$hypervisor\""
    tags: conf

  - name: enable virtio for instance root device
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^USE_VIRTIO_ROOT line=USE_VIRTIO_ROOT="\"$virtio_root\""
    tags: conf

  - name: enable virtio for instance ebs
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^USE_VIRTIO_DISK line=USE_VIRTIO_DISK="\"$virtio_block\""
    tags: conf

  - name: enable virtio for instance network adapters
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^USE_VIRTIO_NET line=USE_VIRTIO_NET="\"$virtio_net\""
    tags: conf

  - name: set public interface
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_PUBINTERFACE= line=VNET_PUBINTERFACE="\"$public_iface\""
    tags: conf

  - name: set bridged interface
    action: lineinfile dest=/etc/eucalyptus/eucalyptus.conf regexp=^VNET_BRIDGE= line=VNET_BRIDGE="\"$bridge\""
    tags: conf
  

#
# BOOTSTRAP COMPONENTS
#

- hosts: clc

  tasks:

  - name: Starting CLC
    action: service name=eucalyptus-cloud enabled=yes state=started
    tags: bootstrap

- hosts: walrus

  tasks:
  
  - name: Starting Walrus
    action: service name=eucalyptus-walrus enabled=yes state=started
    tags: bootstrap

- hosts: cc

  tasks:

  - name: Starting Cluster Controller(s)
    action: service name=eucalyptus-cc enabled=yes state=started
    tags: bootstrap

- hosts: sc

  tasks:

  - name: Starting Storage Controller(s)
    action: service name=eucalyptus-sc enabled=yes state=started
    tags: bootstrap

- hosts: nc

  tasks:

  - name: Starting Node Controller(s)
    action: service name=eucalyptus-nc enabled=yes state=started
    tags: bootstrap
