# Eucalyptus software versions major.minor
euca_version: 3.1
eucatools_version: 2.1
# ~~~~~~~ Eucalyptus.conf variables ~~~~~~~~
# Log level, options: DEBUG, INFO, WARN, ERROR, and FATAL
loglevel: INFO
# Eucalyptus networking mode
network_mode: MANAGED-NOVLAN
# ~~~~~~~ Networking variables ~~~~~~~
# Public interface (used in Eucalyptus networking modes without bridging on the NC)
public_iface: em1
# Whether to use a bridge or not.  This will ultimately be rolled into the networking mode.
use_bridge: yes
# Bridge interface name
bridge: br0
# Interface to add to the bridge
bridge_iface: em1
# Mac address of interface which will be added to the bridge
bridge_mac: ansible_${bridge_iface}.macaddress
# ~~~~~~~ Misc variables ~~~~~~~
# Should the system be registered with RHN?
register_with_rhn: no
# Tuned profile to use
tuned_profile: virtual-host
