# Eucalyptus software versions major.minor
euca_version: 3.2
eucatools_version: 2.1
# ~~~~~~~ Eucalyptus.conf variables ~~~~~~~~
# Log level, options: DEBUG, INFO, WARN, ERROR, and FATAL
loglevel: INFO
# Port for NC to listen on
nc_port: 8775
# Hypervisor, kvm or xen
hypervisor: kvm
# Virtio enablement 1 = on | 0 = off 
virtio_root: 1
virtio_block: 1
virtio_net: 1
# ~~~~~~~ Networking variables ~~~~~~~
# Public interface (used in Eucalyptus networking modes without bridging on the NC)
public_iface: em1
# Whether to use a bridge or not.  This will ultimately be rolled into the networking mode.
use_bridge: yes
# Bridge interface name
bridge: br0
# Interface to add to the bridge
bridge_iface: em2
# Mac address of interface which will be added to the bridge
bridge_mac: ansible_${bridge_iface}.macaddress
# Gateway for NC
nc_gateway: 10.104.0.1
# ~~~~~~~ Misc variables ~~~~~~~
# Should the system be registered with RHN?
register_with_rhn: no
# Tuned profile to use
tuned_profile: virtual-host
