- name: Registering nodes
  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-nodes ${hostvars.{$item}.ansible_br0.ipv4.address}
  with_items: ${groups.nodecontroller}
  tags:
  - nodereg
