- name: initialize the platform
  action: command /usr/sbin/euca_conf --initialize
  notify: 
     - restart cloud services
     
- name: Register Walrus
  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-walrus --partition walrus --host $item.ansible_em1.ipv4.address --component walrus-${item.ansible.hostname}
  with_items: groups.walrus

- name: Register Storage Controller
  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-sc --partition $partition --host $item.ansible_em1.ipv4.address --component sc-${item.ansible.hostname}
  with_items: groups.sc 

- name: Register Cluster Controller
  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-cc --partition $partition --host $item.ansible_em1.ipv4.address --component cc-${item.ansible.hostname}
  with_items: groups.cc

- name: Get Administrator Credentials
  action: command /usr/sbin/euca_conf --get-credentials /root/admin.zip 

- name: Unpack admin credentials
  action: command unzip /root/admin.zip

- name: Source credentials
  action: source /root/eucarc

- name: Configure Storage Backend
  action: command /usr/sbin/euca-modify-properties -p $partition.storage.blockstoragemanager=overlay
