- name: Register Walrus
  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-walrus --partition walrus --host ${hostvars.{$item}.ansible_em1.ipv4.address} --component walrus-${hostvars.{$item}.ansible_hostname}
  with_items: ${groups.walrus} 
  tags:
  - reg
     
- name: Register Storage Controller
  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-sc --partition $partition --host ${hostvars.{$item}.ansible_em1.ipv4.address} --component sc-${hostvars.{$item}.ansible_hostname}
  with_items: ${groups.storagecontroller}
  tags:
  - reg

- name: Register Cluster Controller
  action: command /usr/sbin/euca_conf --no-scp --no-rsync --no-sync --register-cluster --partition $partition --host ${hostvars.{$item}.ansible_em1.ipv4.address} --component cc-${hostvars.{$item}.ansible_hostname}
  with_items: ${groups.clustercontroller}
  tags:
  - reg

- name: Copy keys on single frontend
  action: command cp -f /var/lib/eucalyptus/keys/${partition}/$item /var/lib/eucalyptus/keys/
  with_items: 
  - cluster-cert.pem
  - cluster-pk.pem
  - node-cert.pem
  - node-pk.pem
  - vtunpass
  tags:
  - reg
  - keys

- name: Get Administrator Credentials
  action: command /usr/sbin/euca_conf --get-credentials /root/admin.zip
  tags:
  - creds

- name: Unpack admin credentials
  action: command /usr/bin/unzip -qou /root/admin.zip -d /root/admin-creds
  tags:
  - creds

- name: Source credentials
  action: shell source /root/admin-creds/eucarc && euca-modify-property -p $partition.storage.blockstoragemanager=overlay
  tags:
  - creds
