  - name: Install the Eucalyptus RPMs and deps
    action: yum pkg=$item state=installed
    with_items:
    - eucalyptus-sc
    - libselinux-python
    - tuned
    tags:
    - packages

  - name: disable firewall
    action: service name=iptables enabled=no state=stopped
    tags: networking

  - name: Ensure SElinux is disabled
    action: selinux state=disabled
    tags: tune

  - name: set profile
    action: command tuned-adm profile $tuned_profile
    tags: tune

  - name: set tuned to start on boot
    action: service name=tuned enabled=yes state=started
    tags: tune

  - name: turn on ntp and start on boot
    action: service name=ntpd enabled=yes state=started
    tags: tune

