# ----------------------------------------------------- 
# This playbook is an example for deploying a load of instances which generate LOAD.  They are monkeys. 
# -----------------------------------------------------

- name: Stage instance
  hosts: local
  connection: local
  user: root
  gather_facts: false

  vars:
      keypair: admin
      instance_type: m1.small
      security_group: default
      image: emi-048B3A37 
      count: 5

  tasks:
    - name: Launch instance 
      local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image count=$count wait=true
      register: ec2

    - name: Add new instance to host group
      local_action: add_host hostname=${item.public_ip} groupname=loadmonkeys
      with_items: ${ec2.instances}

#    - name: Itemised host group addition
#      local_action: add_host hostname=${item.public_ip} groupname=launched
#      with_items: ${ec2.instances} 
  
- name: Install packages
  hosts: loadmonkeys
  user: root
  gather_facts: True

  vars:
      io_workers: 1
      cpu_workers: 0
      vm_workers: 0
      duration_secs: 320
      cpu_benchmark: yes
      
  tasks:
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started

    - name: Download the EPEL repo
      action: get_url url=http://downloads.eucalyptus.com/software/eucalyptus/3.2/rhel/6/x86_64/epel-release-6.noarch.rpm dest=/tmp/ thirsty=yes

    - name: Install the EPEL repo
      action: command rpm -Uvh /tmp/epel-release-6.noarch.rpm

    - name: Install stress
      action: yum pkg=stress state=latest
 
    - name: Install bonnie++
      action: yum pkg=bonnie++ state=latest

    - name: Install sysbench
      action: yum pkg=sysbench state=latest

    - name: Run combined stress profile
      action: command /usr/bin/stress -c $cpu_workers -m $vm_workers -i $io_workers -t $duration_secs 
      when_integer: $io_workers > 0 and $cpu_workers > 0 and $vm_workers > 0
      tags: stress

    - name: Run IO stress profile
      action: command /usr/bin/stress -i $io_workers -t $duration_secs
      when_integer: $io_workers > 0 and $cpu_workers == 0 and $vm_workers == 0
      tags: stress
 
    - name: Run CPU stress profile 
      action: command /usr/bin/stress -c $cpu_workers -t $duration_secs
      when_integer: $cpu_workers > 0 and $io_workers == 0 and $vm_workers == 0
      tags: stress

    - name: Run VM stress profile
      action: command /usr/bin/stress -c $vm_workers -t $duration_secs
      when_integer: $vm_workers > 0 and $cpu_workers == 0 and $io_workers == 0
      tags: stress

    - name: Benchmark CPU
      action: command /usr/bin/sysbench --test=cpu run
      when_string: $cpu_benchmark == 'yes'
      tags: benchmark 

# Use this section for a mail notification when instance configuration is complete. 
# You need to set the mail_from and mail_to vars.
#  - name: Send e-mail to admins
#    local_action: mail
#        from=${mail_from}
#       to=${mail_to}
#      subject="EC2 instance (${shortname}) ${ec2.instances[0].id}. LOADMONKEYS ARE OUT!"
#        body="EC2 instance ${ec2.instances[0].id} created on ${ec2.instances[0].public_ip} running LOAD."


