# ----------------------------------------------------- 
# This playbook is an example for deploying multiple instances into EC2/Euca and "doing something" with them
# Run this with ansible-playbook and supply the private key for your EC2/Euca user (to access the instance in the second play), e.g:
# ansible-playbook eucalyptus-ec2-deploy.yml -v --private-key=/path/to/ec2/pri/key
# -----------------------------------------------------

- name: Stage instance(s)
  hosts: local
  connection: local
  user: root
  gather_facts: false

  vars:
      keypair: mykeypair
      instance_type: m1.small
      security_group: default
      image: emi-048B3A37

  tasks:
    - name: Launch instance 
      local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image wait=true 
      register: ec2
     
    - name: Add new instances to host group
      local_action: add_host hostname=${item.public_ip} groupname=deploy
      with_items: ${ec2.instances}

    - name: Wait for a while before trying to configure instances
      local_action: pause minutes=1

- name: Configure instance
  hosts: deploy
  user: root
  gather_facts: True

  tasks:
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started
   
    - name: Install Apache Web Server
      action: yum pkg=httpd state=latest
