- name: Stage instance
  hosts: local
  connection: local
  user: root 
  gather_facts: false

  vars:
      keypair: lwade
      instance_type: m1.small
      security_group: sg-c4e4d7ac 
      image: ami-cc5af9a5 
      group_ids: sg-eb267883
#      mail_from: ansible@localhost
#      mail_to: root@localhost

  tasks:
     - name: Upload something to S3
       local_action: s3 bucket=ansiblebucket filename=/tmp/s3test action=put state=present key=rename 
       register: s3
     
     - name: debug msg
       local_action: debug msg="S3 url is ${s3.url}"

#    - name: Launch instance 
#      local_action: ec2 keypair=$keypair group=default instance_type=$instance_type image=$image wait=true instance_tags='{"my":"stuff"}' 
#     register: ec2

#    - name: Itemised host group addition
#      local_action: add_host hostname=${item.public_ip} groupname=launched
#      with_items: ${ec2.instances} 

#    - name: Pause
#      local_action: pause minutes=3
     
#    - name: Add first instance to host group
#      local_action: add_host hostname=${ec2.instances[0].public_ip} groupname=launched
#    - name: Debug

#      local_action: debug msg="The second instance has ${ec2.instances[1].public_ip}"
#    - name: Launch a load of instances

#    - name: Create and attach volume
#      local_action: ec2_vol instance=${item.id} volume_size=5 
#      with_items: ${ec2.instances}
#      register: ec2_vol
    
#    - name: Report
#      local_action: debug msg="${ec2_vol.volume_id}"
  
- name: Install packages
  hosts: launched
  user: root
  gather_facts: true

  tasks:
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started
