- name: Stage instance
  hosts: local
  connection: local
  user: root 
  gather_facts: false

  vars:
      keypair: lwade
      instance_type: m1.small
      security_group: sg-c4e4d7ac 
      image: ami-00c83b69
      group_ids: sg-eb267883
#      mail_from: ansible@localhost
#      mail_to: root@localhost

  tasks:
#    - name: Launch instance 
#      local_action: ec2 keypair=$keypair group=default instance_type=$instance_type image=$image wait=true instance_tags='{"my":"stuff"}' 
#      register: ec2

#    - name: Itemised host group addition
#      local_action: add_host hostname=${item.public_ip} groupname=launched
#      with_items: ${ec2.instances} 
     
#    - name: Add first instance to host group
#      local_action: add_host hostname=${ec2.instances[0].public_ip} groupname=launched
#    - name: Debug
#      local_action: debug msg="The second instance has ${ec2.instances[1].public_ip}"
    - name: Launch a load of instances
      local_action: ec2 keypair=$keypair instance_type=$instance_type image=$image wait=true count=1 group=win-sg-1
      register: ec2

#    - name: Create a volume and attach
#      local_action: ec2_vol volume_size=1 instance=${item.id} 
#      with_items: ${ec2.instances}
#      register: ec2_vol

#    - name: Create and attach volume
#      local_action: ec2_vol instance=${item.id} volume_size=5 
#      with_items: ${ec2.instances}
#      register: ec2_vol
    
#    - name: Report
#      local_action: debug msg="${ec2_vol.volume_id}"
  
- name: Install packages
  hosts: launched
  user: root
  gather_facts: true

  vars:
      io_workers: 1
      cpu_workers: 0
      vm_workers: 0
      duration_secs: 320
      cpu_benchmark: yes
      
  tasks:
    - name: Ensure NTP is up and running
      action: service name=ntpd state=started

    - name: Download the EPEL repo
      action: get_url url=http://downloads.eucalyptus.com/software/eucalyptus/3.2/rhel/6/x86_64/epel-release-6.noarch.rpm dest=/tmp/ thirsty=yes

    - name: Install the EPEL repo
      action: command rpm -Uvh /tmp/epel-release-6.noarch.rpm

    - name: Install stress
      action: yum pkg=stress state=latest
 
    - name: Install bonnie++
      action: yum pkg=bonnie++ state=latest

    - name: Install sysbench
      action: yum pkg=sysbench state=latest

    - name: Run combined stress profile
      action: command /usr/bin/stress -c $cpu_workers -m $vm_workers -i $io_workers -t $duration_secs 
#      when_set: $io_workers and $cpu_workers and $vm_workers
      when_integer: $io_workers > 0 and $cpu_workers > 0 and $vm_workers > 0
      tags: stress

    - name: Run IO stress profile
      action: command /usr/bin/stress -i $io_workers -t $duration_secs
#      when_unset: $cpu_workers and $vm_workers
      when_integer: $io_workers > 0 and $cpu_workers == 0 and $vm_workers == 0
      tags: stress
 
    - name: Run CPU stress profile 
      action: command /usr/bin/stress -c $cpu_workers -t $duration_secs
#      when_unset: $io_workers and $vm_workers
      when_integer: $cpu_workers > 0 and $io_workers == 0 and $vm_workers == 0
      tags: stress

    - name: Run VM stress profile
      action: command /usr/bin/stress -c $vm_workers -t $duration_secs
#      when_unset: $cpu_workers and $io_workers
      when_integer: $vm_workers > 0 and $cpu_workers == 0 and $io_workers == 0
      tags: stress

    - name: Benchmark CPU
      action: command /usr/bin/sysbench --test=cpu run
      when_string: $cpu_benchmark == 'yes'
      tags: benchmark 

#  - name: Send e-mail to admins
#    local_action: mail
#        from=${mail_from}
#       to=${mail_to}
#      subject="EC2 instance (${shortname}) ${ec2.instances[0].id}"
#        body="EC2 instance ${ec2.instances[0].id} created on ${ec2.instances[0].public_ip}"


